### ISSUE TITLE
Count all hashing ops against the hashing limit (don't exclude CHECKSIG)

### ISSUE THREAD

**Issue by A60AB5450353F40E** [bitjson/bch-vm-limits#16]
Adversary with access to hashrate could prepare TXs that each add up to something like 180 MB: preparing a bunch of non-standard 10k long UTXOs and spending as much of them as can fit in a 1MB non-standard TX.

Most inputs could be sigless, just some OP_1, but it takes only 1 CHECKSIG with SIGHASH_UTXOs input to have to hash the whole TX and all its prevouts.

**Comment by cculianu** [comment]
Counterpoint: Hmm. Given the existence of SIGHASH_UTXOs.. if we were to have OP_CHECKSIG* count towards hashing limit -- we may end up making txns that are perfectly OK now.. no longer possible. Hmm.

This could be a good thing or a bad thing. No idea.

However --  I thought the point of spec was to liberalize ... not create new tighter constraints on things..

**Comment by A60AB5450353F40E** [comment]
btw didn't we have a talk about this when sighash_utxos was being introduced and discovered all is fine, although I forgot the rationale, hashing is just so fast it's not a problem?

**Comment by cculianu** [comment]
Yes but -- I am saying the new proposed 1000 hashops limit -- if it were to count towards OP_CHECKSIG, would make txns that currently are OK -- no longer valid. 😟 

Also.. in a single OP_CHECKSIG you have multiple hashes going into the final sigHash... it can get messy. :P

**Comment by bitjson** [comment]
Hi all! Cleaning up issues now that we have two implementations of the latest proposal. 🚀

The latest version of the proposal now limits a portion of the hashing required during signature checking (specifically to resolve the [open issue with abuse of `OP_CODESEPARATOR`](https://github.com/bitjson/bch-vm-limits/issues/9)).

The collection of issues around signature checking also now makes up a significant chunk of the CHIP's rationale section:

- [Rationale: Exclusion of Signing Serialization Components from Hashing Limit](https://github.com/bitjson/bch-vm-limits/blob/b476674575e0f5d2ccdf60d5091a3b882b38b00c/rationale.md#exclusion-of-signing-serialization-components-from-hashing-limit) - (the most relevant rationale WRT this issue)
- [Rationale: Ongoing Value of OP_CODESEPARATOR Operation](https://github.com/bitjson/bch-vm-limits/blob/b476674575e0f5d2ccdf60d5091a3b882b38b00c/rationale.md#ongoing-value-of-op_codeseparator-operation)
- [Rationale: Selection of Signature Verification Operation Cost](https://github.com/bitjson/bch-vm-limits/blob/b476674575e0f5d2ccdf60d5091a3b882b38b00c/rationale.md#selection-of-signature-verification-operation-cost)
- [Rationale: Continued Availability of Deferred Signature Validation](https://github.com/bitjson/bch-vm-limits/blob/b476674575e0f5d2ccdf60d5091a3b882b38b00c/rationale.md#continued-availability-of-deferred-signature-validation)

And for future readers, I'll just clarify a bit:

> btw didn't we have a talk about this when sighash_utxos was being introduced and discovered all is fine [...] ?

Yes, this cost is covered by the previous transaction fee(s) paid for the bandwidth/storage to set up these large, nonstandard UTXOs (in practice, paid by the miner's opportunity cost and/or stale block risk).

In any case, we don't have to worry much about signing serialization components (i.e. `hashPrevouts`, `hashUtxos`, `hashSequence`, and `hashOutputs`) because:

 1. They're highly cache-able across the whole transaction (or at least the whole input, in the case of `hashOuputs` with `SIGHASH_SINGLE`). 
 2. The per-byte cost of racking up hashing is much worse for an attacker: even with a standard hashing limit of `0.5` hash digest iterations per byte, an attacker is still paying an order of magnitude more per hash digest iteration to make validating nodes hash any signing serialization component (where the attacker can't magnify their attack by forcing the nodes to work on short messages/maximize padding within each hash digest iteration).

Thanks for opening the issue @A60AB5450353F40E! I'm going to mark this as resolved, but please comment if I should re-open.
